[package]
name = "tiso-os"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
argon2 = { version = "0.5.3", features = ["std"] }
async-trait = "0.1.89"
axum = { version = "0.8.9", features = ["macros", "multipart", "ws"] }
axum-extra = { version = "0.12.6", features = ["cookie"] }
base64 = "0.22.1"
csscolorparser = "0.8.3"
deadpool-postgres = "0.14.1"
ego-tree = "0.11.0"
memory-serve = { version = "2.1.0" }
papaya = "0.2.4"
postgres-types = { version = "0.2.13", features = ["derive"] }
rand = { version = "0.10.1", features = ["thread_rng"] }
regex = "1.12.3"
sailfish = "0.11.1"
scraper = "0.27.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
tempfile = "3.27.0"
time = "0.3.47"
tokio = { version = "1.52.3", features = ["macros", "process", "rt-multi-thread"] }
tokio-postgres = { version = "0.7.17", features = ["with-serde_json-1", "with-time-0_3"] }
tower-http = { version = "0.6.11", features = [
  "compression-zstd",
  "fs",
  "set-header",
  "trace",
] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
uuid = { version = "1.23.1", features = ["fast-rng", "v4"] }
zip = "8.6.0"

[build-dependencies]
dotenvy = "0.15.7"
memory-serve = "2.1.0"

[profile.release]
debug = false
lto = true
opt-level = "z"
panic = 'abort'
codegen-units = 1
