services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DBNAME}
    volumes:
      - tiso_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: "False"
    ports:
      - 15432:80
    volumes:
      - tiso_pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
  nginx:
    build:
      context: ../../
      dockerfile: ./infra/nginx/Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ../../nginx.conf:/etc/nginx/nginx.conf
      - ../../assets:/usr/share/nginx/assets
    depends_on:
      - tiso
  tiso:
    build:
      context: ../../
      dockerfile: ./infra/dev/Dockerfile
    env_file:
      - .env
    volumes:
      - ../../:/app
      - tiso_cargo-target:/app/target
    depends_on:
      - postgres

volumes:
  tiso_pgdata:
  tiso_pgadmin:
  tiso_cargo-target:
