services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DBNAME}
    volumes:
      - tiso_pgdata:/var/lib/postgresql/data
  nginx:
    build:
      context: ../../
      dockerfile: ./infra/nginx/Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ../../nginx.conf:/etc/nginx/nginx.conf
      - ../../assets:/usr/share/nginx/assets
    depends_on:
      - tiso
  tiso:
    build:
      context: ../../
      dockerfile: ./infra/prod/Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  tiso_pgdata:
